name: Build and Deploy Worker

on:
  push:
    branches:
      - main

env:
  SERVICE: 'jobmatch-worker'
  PROJECT_ID: 'n3xtbridge'
  REGION: 'us-east1'
  IMAGE: 'muhammadolammi/jobmatch-worker'
  


permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build and Push Worker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Build the server binary
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          DEPLOY_VERSION=$(git rev-parse --short HEAD)
          docker build -t $IMAGE:latest -t $IMAGE:$DEPLOY_VERSION .
          docker push $IMAGE --all-tags

  deploy:
    needs: build
    name: Deploy Worker to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          project_id: ${{ env.PROJECT_ID }}
          image: index.docker.io/${{ env.IMAGE }}:latest
          env_vars: |
            PROJECT_ID=${{ env.PROJECT_ID }}
            DB_URL=${{ secrets.DB_URL }}
            RABBITMQ_URL=${{ secrets.RABBITMQ_URL }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
            R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }}
            R2_BUCKET=${{ secrets.R2_BUCKET }}
            R2_SECRET_KEY=${{ secrets.R2_SECRET_KEY }}
            R2_ACCESS_KEY=${{ secrets.R2_ACCESS_KEY }}